### PR TITLE
Updated to specify publicly available dependency for the go plugin api jar.

### PR DESCRIPTION
**Pull request by ghost**
The previous groupId would not work.

Also corrected url for documentation for developers of plugins, as the previous URL leads to a 404 error.

### CODE REVIEW

**Comment by arvindsv** [comment]
@stephen-souness-springer: Yes, makes sense. I can accept it, but before that, can you please sign the [CLA](http://www.go.cd/contribute/cla.html)? It's a legal requirement, and is one-time only. Thank you!

**Comment by ghost** [comment]
CLA form submitted.

**Comment by arvindsv** [comment]
Thank you! Merged.

**Pull request merged**
